"""
Batch 2: 12 academic PDFs for larger ingestion test.
Creates PDFs with reportlab, uploads via TestClient API.
"""
import sys, os, json
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

MATERIALS = [
    {"file":"DBMS_Notes.pdf","title":"Database Management Systems","subject":"Computer Science","semester":"3","content":"Database Management Systems Notes. Chapter 1: Introduction to DBMS. A Database Management System is software that manages databases. It provides an interface between data and applications. The DBMS handles data storage retrieval and update operations efficiently. Key advantages include data independence redundancy control concurrent access and data integrity. The three-schema architecture separates external conceptual and internal levels. Data models include hierarchical network relational and object-oriented. Edgar Codd proposed the relational model in 1970 which organizes data into tables with rows and columns. Primary keys uniquely identify each record. Foreign keys establish relationships between tables. Chapter 2: Relational Algebra. Relational algebra provides a formal foundation for SQL operations. Selection sigma filters rows based on conditions. Projection pi selects specific columns. Join combines tuples from two relations based on a condition. Natural join matches on common attributes. Set operations include union intersection and difference. Division finds tuples in one relation that match all tuples in another. Chapter 3: SQL Fundamentals. SQL is a declarative language for managing relational databases. DDL commands include CREATE ALTER and DROP for schema definition. DML commands include SELECT INSERT UPDATE and DELETE for data manipulation. The SELECT statement retrieves data using FROM WHERE GROUP BY HAVING and ORDER BY clauses. Aggregate functions include COUNT SUM AVG MIN and MAX. Subqueries can be correlated or uncorrelated. Views are virtual tables derived from base tables. Chapter 4: Normalization. Normalization reduces data redundancy and prevents anomalies. First Normal Form 1NF eliminates repeating groups. Second Normal Form 2NF removes partial dependencies. Third Normal Form 3NF eliminates transitive dependencies. Boyce-Codd Normal Form BCNF handles additional anomalies beyond 3NF. Functional dependencies determine the normal form of a relation. Decomposition must be lossless and dependency-preserving."},
    {"file":"OS_Notes.pdf","title":"Operating Systems Concepts","subject":"Computer Science","semester":"4","content":"Operating Systems Concepts. Chapter 1: Introduction. An operating system is system software that manages computer hardware and software resources. It provides services for application programs and acts as an intermediary between users and hardware. Key functions include process management memory management file system management device management and security. Types include batch multiprogramming time-sharing distributed and real-time operating systems. Chapter 2: Process Management. A process is a program in execution with its own address space program counter and registers. Process states include new ready running waiting and terminated. The Process Control Block PCB stores process information. Context switching saves and restores process state. Process scheduling algorithms include First Come First Served FCFS Shortest Job First SJF Priority Scheduling and Round Robin. Preemptive scheduling allows interruption of running processes. Chapter 3: Memory Management. Memory management allocates and deallocates memory space to processes. Contiguous allocation assigns consecutive memory blocks. Paging divides memory into fixed-size frames and processes into pages. Page tables map logical to physical addresses. Segmentation divides memory based on logical segments. Virtual memory allows execution of processes larger than physical memory using demand paging. Page replacement algorithms include FIFO LRU and Optimal. Thrashing occurs when excessive paging degrades performance. Chapter 4: File Systems. File systems organize and store data on storage devices. Directory structures include single-level two-level tree and acyclic graph. File allocation methods include contiguous linked and indexed allocation. Free space management uses bit vectors linked lists grouping and counting."},
    {"file":"CN_Notes.pdf","title":"Computer Networks Fundamentals","subject":"Computer Science","semester":"4","content":"Computer Networks Fundamentals. Chapter 1: Introduction to Networking. A computer network connects devices to share resources and communicate. Networks are classified by size as LAN MAN and WAN. Topologies include bus star ring mesh and hybrid. The OSI model has seven layers Physical Data Link Network Transport Session Presentation and Application. The TCP/IP model has four layers Network Interface Internet Transport and Application. Chapter 2: Physical and Data Link Layer. The physical layer handles bit transmission over physical media including copper fiber and wireless. Encoding schemes convert data into signals. The data link layer provides node-to-node delivery error detection and flow control. Framing adds headers and trailers. Error detection uses parity CRC and checksum. Flow control mechanisms include stop-and-wait and sliding window protocols. MAC sublayer handles media access using CSMA/CD for Ethernet and CSMA/CA for WiFi. Chapter 3: Network Layer. The network layer provides host-to-host delivery through routing and logical addressing. IPv4 uses 32-bit addresses organized into classes A through E. Subnetting divides networks into smaller segments using subnet masks. IPv6 uses 128-bit addresses to solve address exhaustion. Routing algorithms include distance vector and link state. Routing protocols include RIP OSPF and BGP. Chapter 4: Transport Layer. TCP provides reliable connection-oriented byte-stream service with flow control congestion control and error recovery. UDP provides unreliable connectionless datagram service for speed-sensitive applications. Port numbers identify application processes. The three-way handshake establishes TCP connections using SYN SYN-ACK and ACK segments."},
    {"file":"DAA_Notes.pdf","title":"Design and Analysis of Algorithms","subject":"Computer Science","semester":"4","content":"Design and Analysis of Algorithms. Chapter 1: Algorithm Analysis. An algorithm is a finite sequence of well-defined instructions to solve a problem. Time complexity measures computational time as a function of input size. Space complexity measures memory usage. Asymptotic notations include Big-O upper bound Big-Omega lower bound and Big-Theta tight bound. Common complexities are O(1) O(log n) O(n) O(n log n) O(n squared) and O(2 to the n). Amortized analysis averages cost over a sequence of operations. Chapter 2: Divide and Conquer. Divide and conquer breaks problems into smaller subproblems solves them recursively and combines results. Merge Sort divides the array recursively and merges sorted halves achieving O(n log n) time. Quick Sort selects a pivot partitions elements and recurses on partitions. Binary Search achieves O(log n) by halving the search space. Strassen matrix multiplication reduces complexity from O(n cubed) to O(n to the 2.81). Chapter 3: Dynamic Programming. Dynamic programming solves problems with overlapping subproblems and optimal substructure. Memoization stores computed results top-down. Tabulation builds solutions bottom-up. Classic problems include Fibonacci sequence longest common subsequence matrix chain multiplication knapsack problem and shortest paths. Bellman-Ford algorithm finds shortest paths with negative weights. Floyd-Warshall finds all-pairs shortest paths. Chapter 4: Greedy Algorithms. Greedy algorithms make locally optimal choices hoping for global optimum. Activity selection chooses maximum non-overlapping activities. Huffman coding creates optimal prefix codes for data compression. Kruskal and Prim algorithms find minimum spanning trees. Dijkstra algorithm finds shortest paths from a single source."},
    {"file":"SE_Notes.pdf","title":"Software Engineering Principles","subject":"Computer Science","semester":"5","content":"Software Engineering Principles. Chapter 1: Introduction. Software engineering applies engineering principles to software development. The software crisis of the 1960s highlighted the need for systematic approaches. Key challenges include complexity conformity changeability and invisibility. Software process models provide frameworks for organizing development activities. Chapter 2: Software Development Life Cycle. The Waterfall model follows sequential phases requirements design implementation testing and maintenance. The Spiral model combines iterative development with risk analysis. Agile methodologies emphasize iterative delivery collaboration and adaptability. Scrum uses sprints product backlogs and daily standups. Extreme Programming XP practices include pair programming test-driven development and continuous integration. Chapter 3: Requirements Engineering. Requirements engineering involves elicitation analysis specification and validation. Functional requirements describe system behavior and features. Non-functional requirements specify quality attributes like performance reliability and security. Use case diagrams model interactions between actors and the system. Software Requirements Specification SRS documents all requirements formally. Chapter 4: Software Design. Software design transforms requirements into a blueprint for implementation. Architectural design defines system structure and component interactions. Design patterns provide reusable solutions to common problems including creational structural and behavioral patterns. The SOLID principles guide object-oriented design Single Responsibility Open-Closed Liskov Substitution Interface Segregation and Dependency Inversion. Coupling measures interdependence between modules while cohesion measures relatedness within modules."},
    {"file":"Probability_Notes.pdf","title":"Probability and Statistics","subject":"Mathematics","semester":"3","content":"Probability and Statistics. Chapter 1: Probability Theory. Probability measures the likelihood of an event occurring on a scale from 0 to 1. The sample space is the set of all possible outcomes. Events are subsets of the sample space. The addition rule states P(A union B) equals P(A) plus P(B) minus P(A intersection B). The multiplication rule for independent events states P(A intersection B) equals P(A) times P(B). Conditional probability P(A given B) equals P(A intersection B) divided by P(B). Bayes theorem relates conditional probabilities P(A given B) equals P(B given A) times P(A) divided by P(B). Chapter 2: Random Variables. A random variable assigns numerical values to outcomes. Discrete random variables take countable values. Continuous random variables take values in an interval. The probability mass function PMF gives probabilities for discrete variables. The probability density function PDF describes continuous distributions. Expected value E(X) is the weighted average of possible values. Variance Var(X) measures spread around the mean. Standard deviation is the square root of variance. Chapter 3: Probability Distributions. The binomial distribution models the number of successes in n independent trials. The Poisson distribution models rare events in a fixed interval. The normal distribution is bell-shaped and characterized by mean and standard deviation. The central limit theorem states that sample means approach a normal distribution regardless of population distribution. The exponential distribution models time between events in a Poisson process. Chapter 4: Statistical Inference. Point estimation provides single value estimates of population parameters. Confidence intervals give ranges of plausible parameter values. Hypothesis testing evaluates claims about population parameters using test statistics and p-values. Type I error rejects a true null hypothesis. Type II error fails to reject a false null hypothesis."},
    {"file":"Discrete_Math.pdf","title":"Discrete Mathematics","subject":"Mathematics","semester":"2","content":"Discrete Mathematics. Chapter 1: Set Theory and Logic. A set is a well-defined collection of distinct objects. Set operations include union intersection complement and difference. De Morgan laws relate complement of union and intersection. Propositional logic uses logical connectives AND OR NOT implication and biconditional. Truth tables evaluate compound propositions. Logical equivalences include commutativity associativity distributivity and contrapositive. Predicate logic extends propositional logic with quantifiers universal for all and existential there exists. Chapter 2: Relations and Functions. A relation on sets A and B is a subset of the Cartesian product A times B. Properties include reflexive symmetric transitive and antisymmetric. An equivalence relation is reflexive symmetric and transitive. A partial order is reflexive antisymmetric and transitive. Functions map elements from domain to codomain. Types include injective one-to-one surjective onto and bijective both. Composition of functions applies one function after another. Chapter 3: Combinatorics. The counting principle states that if one event has m outcomes and another has n outcomes the total is m times n. Permutations count ordered arrangements P(n,r) equals n factorial divided by (n-r) factorial. Combinations count unordered selections C(n,r) equals n factorial divided by r factorial times (n-r) factorial. The pigeonhole principle states that if n items are placed in m containers with n greater than m then at least one container has more than one item. Inclusion-exclusion counts elements in unions of sets. Chapter 4: Graph Theory. A graph consists of vertices and edges. Degree of a vertex is the number of incident edges. Euler paths traverse every edge exactly once. Hamiltonian paths visit every vertex exactly once. Planar graphs can be drawn without edge crossings. Graph coloring assigns colors so adjacent vertices differ. Trees are connected acyclic graphs with n-1 edges for n vertices."},
    {"file":"Linear_Algebra.pdf","title":"Linear Algebra Essentials","subject":"Mathematics","semester":"3","content":"Linear Algebra Essentials. Chapter 1: Vectors and Matrices. A vector is an ordered list of numbers representing magnitude and direction. Vector operations include addition scalar multiplication and dot product. The dot product of vectors a and b equals the sum of products of corresponding components. The cross product produces a vector perpendicular to both input vectors. A matrix is a rectangular array of numbers arranged in rows and columns. Matrix operations include addition scalar multiplication and matrix multiplication. The transpose of matrix A denoted A superscript T swaps rows and columns. Chapter 2: Systems of Linear Equations. A system of linear equations can be represented as Ax equals b. Gaussian elimination reduces the augmented matrix to row echelon form. Back substitution solves the system from the bottom up. A system has a unique solution no solution or infinitely many solutions. The rank of a matrix equals the number of non-zero rows in row echelon form. Chapter 3: Determinants and Inverses. The determinant of a 2x2 matrix ad minus bc. For larger matrices use cofactor expansion along any row or column. Properties include det(AB) equals det(A) times det(B) and det(A transpose) equals det(A). A matrix is invertible if and only if its determinant is non-zero. The inverse satisfies A times A-inverse equals the identity matrix. Cramer rule uses determinants to solve systems of linear equations. Chapter 4: Eigenvalues and Eigenvectors. An eigenvector v satisfies Av equals lambda v where lambda is the eigenvalue. The characteristic equation det(A minus lambda I) equals 0 gives eigenvalues. Eigenvectors form the eigenspace for each eigenvalue. Diagonalization expresses A as P times D times P-inverse where D is diagonal. Applications include solving differential equations and principal component analysis."},
    {"file":"AI_Intro.pdf","title":"Introduction to Artificial Intelligence","subject":"Computer Science","semester":"6","content":"Introduction to Artificial Intelligence. Chapter 1: Foundations of AI. Artificial intelligence is the study of creating intelligent machines that can perform tasks requiring human intelligence. The field was founded at the Dartmouth Conference in 1956. AI approaches include symbolic AI connectionism and statistical learning. The Turing Test proposed by Alan Turing evaluates machine intelligence through natural language conversation. Types of AI include narrow AI designed for specific tasks and general AI with human-level reasoning. Chapter 2: Search Algorithms. Search algorithms explore state spaces to find solutions. Uninformed search strategies include breadth-first search depth-first search and uniform-cost search. Informed search uses heuristics to guide exploration. A-star search combines path cost and heuristic estimate guaranteeing optimal solutions with admissible heuristics. Hill climbing is a local search method that moves toward better neighboring states. Simulated annealing escapes local optima by occasionally accepting worse solutions. Genetic algorithms use selection crossover and mutation to evolve solutions. Chapter 3: Knowledge Representation. Knowledge representation encodes information for AI systems to reason about. Propositional logic represents facts using boolean variables. First-order logic adds predicates quantifiers and variables for richer representation. Semantic networks represent knowledge as graphs of concepts and relationships. Frames organize knowledge into structured objects with slots and fillers. Ontologies define formal vocabularies and relationships for knowledge domains. Chapter 4: Machine Learning Basics. Machine learning enables systems to learn from data without explicit programming. Supervised learning uses labeled training data for classification and regression. Unsupervised learning discovers patterns in unlabeled data through clustering and dimensionality reduction. Reinforcement learning trains agents through rewards and penalties. Neural networks model computation using layers of interconnected nodes. Deep learning uses multiple hidden layers to learn hierarchical representations. Backpropagation adjusts weights by computing gradients of the loss function."},
    {"file":"Web_Dev.pdf","title":"Web Development Technologies","subject":"Computer Science","semester":"5","content":"Web Development Technologies. Chapter 1: HTML and CSS. HTML HyperText Markup Language defines the structure of web pages using elements and tags. Semantic elements like header nav main article and footer improve accessibility and SEO. CSS Cascading Style Sheets controls visual presentation including layout colors typography and animations. The box model defines content padding border and margin for each element. Flexbox provides one-dimensional layouts while CSS Grid enables two-dimensional layouts. Media queries create responsive designs that adapt to different screen sizes. Chapter 2: JavaScript and DOM. JavaScript is a dynamic interpreted programming language for web interactivity. Variables can be declared with var let and const. Functions are first-class objects that can be assigned to variables and passed as arguments. The Document Object Model DOM represents HTML as a tree of nodes that JavaScript can manipulate. Event handling responds to user interactions like clicks keypresses and form submissions. Asynchronous programming uses callbacks promises and async/await for non-blocking operations. Chapter 3: Backend Development. Server-side programming handles business logic data processing and API endpoints. Node.js runs JavaScript on the server using the V8 engine. Express.js is a minimal web framework for building APIs and web applications. RESTful APIs follow conventions using HTTP methods GET POST PUT DELETE for CRUD operations. Authentication verifies user identity using tokens sessions or OAuth. Database integration connects applications to SQL or NoSQL databases. Chapter 4: Modern Frameworks. React is a component-based library for building user interfaces using JSX and virtual DOM. Angular is a full-featured framework with TypeScript dependency injection and two-way data binding. Vue.js is a progressive framework with reactive data binding and component architecture. Single page applications load once and dynamically update content without full page reloads. State management solutions like Redux and Vuex handle complex application state."},
    {"file":"Cyber_Security.pdf","title":"Cybersecurity Fundamentals","subject":"Computer Science","semester":"6","content":"Cybersecurity Fundamentals. Chapter 1: Security Principles. Cybersecurity protects systems networks and data from digital attacks. The CIA triad encompasses Confidentiality Integrity and Availability. Defense in depth layers multiple security controls. The principle of least privilege grants minimum necessary access. Security policies define organizational rules for protecting information assets. Risk management identifies assesses and mitigates threats to acceptable levels. Chapter 2: Cryptography. Cryptography secures communication through mathematical algorithms. Symmetric encryption uses the same key for encryption and decryption including AES and DES algorithms. Asymmetric encryption uses public-private key pairs including RSA and Elliptic Curve algorithms. Hash functions produce fixed-length digests from variable-length inputs including SHA-256 and MD5. Digital signatures verify authenticity and integrity using private key signing and public key verification. Certificate authorities issue digital certificates binding public keys to identities. TLS protocol secures internet communications using certificate verification key exchange and symmetric encryption. Chapter 3: Network Security. Firewalls filter network traffic based on rules and policies. Intrusion Detection Systems IDS monitor network traffic for suspicious activity. Virtual Private Networks VPNs create encrypted tunnels over public networks. Network segmentation isolates critical systems and limits lateral movement. DNS security prevents cache poisoning and domain hijacking attacks. Chapter 4: Common Attacks. Malware includes viruses worms trojans ransomware and spyware. Phishing uses deceptive emails and websites to steal credentials. SQL injection exploits database queries through unsanitized user input. Cross-site scripting XSS injects malicious scripts into web pages. Denial of service DoS attacks overwhelm systems with excessive traffic. Man-in-the-middle attacks intercept communications between two parties. Social engineering manipulates people into revealing sensitive information."},
    {"file":"Cloud_Computing.pdf","title":"Cloud Computing Architecture","subject":"Computer Science","semester":"6","content":"Cloud Computing Architecture. Chapter 1: Cloud Fundamentals. Cloud computing delivers computing services over the internet on a pay-per-use basis. Key characteristics include on-demand self-service broad network access resource pooling rapid elasticity and measured service. Service models include Infrastructure as a Service IaaS Platform as a Service PaaS and Software as a Service SaaS. Deployment models include public private hybrid and community clouds. Major providers include Amazon Web Services AWS Microsoft Azure and Google Cloud Platform. Chapter 2: Virtualization. Virtualization abstracts physical hardware into virtual resources. Hypervisors manage virtual machines with Type 1 running on bare metal and Type 2 running on host OS. Containers provide lightweight isolation sharing the host kernel using Docker and container orchestration with Kubernetes. Serverless computing executes functions without managing infrastructure using services like AWS Lambda. Microservices architecture decomposes applications into small independently deployable services. Chapter 3: Cloud Storage and Databases. Object storage like S3 stores unstructured data with high durability and availability. Block storage provides raw storage volumes for virtual machines. Cloud databases include relational services like RDS and NoSQL options like DynamoDB and CosmosDB. Data replication ensures availability across multiple geographic regions. Content Delivery Networks CDNs cache content at edge locations for faster delivery. Chapter 4: Cloud Security and DevOps. Identity and Access Management IAM controls who can access cloud resources. Encryption protects data at rest and in transit. Compliance frameworks include SOC 2 ISO 27001 HIPAA and GDPR. DevOps practices integrate development and operations for faster delivery. CI/CD pipelines automate building testing and deploying applications. Infrastructure as Code IaC manages cloud resources through configuration files using Terraform and CloudFormation."},
]

def create_pdf(filepath, title, content):
    c = canvas.Canvas(filepath, pagesize=A4)
    w, h = A4
    margin = 72
    y = h - margin
    line_height = 14
    max_width = w - 2 * margin
    
    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(margin, y, title)
    y -= 30
    c.setFont("Helvetica", 10)
    
    words = content.split()
    line = ""
    for word in words:
        test = line + " " + word if line else word
        if c.stringWidth(test, "Helvetica", 10) < max_width:
            line = test
        else:
            c.drawString(margin, y, line)
            y -= line_height
            line = word
            if y < margin:
                c.showPage()
                c.setFont("Helvetica", 10)
                y = h - margin
    if line:
        c.drawString(margin, y, line)
    c.save()

# Create all PDFs
for m in MATERIALS:
    create_pdf(m["file"], m["title"], m["content"])
    size = os.path.getsize(m["file"])
    print(f"Created: {m['file']} ({size} bytes)")

# Authenticate
login_resp = client.post("/api/v1/auth/login", data={
    "username": "rohit.ghosh@mca.christuniversity.in",
    "password": "Rockstar@00112233"
})
token = login_resp.json().get("access_token")
if not token:
    print("FATAL: Login failed"); sys.exit(1)
headers = {"Authorization": f"Bearer {token}"}
print("Authenticated successfully.")

# Upload
uploaded = []
for m in MATERIALS:
    with open(m["file"], "rb") as f:
        resp = client.post("/api/v1/materials", headers=headers,
            data={"title":m["title"],"description":"Batch 2 academic material",
                  "subject":m["subject"],"course":"BCA","semester":m["semester"],"category":"NOTES"},
            files={"file": (m["file"], f, "application/pdf")})
    if resp.status_code == 201:
        d = resp.json()
        uploaded.append(d)
        print(f"Uploaded: {m['title']} -> {d['id']}")
    else:
        print(f"FAILED: {m['title']} -> {resp.status_code}: {resp.json()}")

report = {"batch":2,"uploaded":len(uploaded),"total_attempted":len(MATERIALS),
          "materials":[{"id":m["id"],"title":m["title"]} for m in uploaded]}
with open("batch2_report.json","w") as f:
    json.dump(report, f, indent=2)
print(f"\nBatch 2 Upload: {len(uploaded)}/{len(MATERIALS)} materials.")
