"""
alembic/script.py.mako
───────────────────────
Template used by `alembic revision` to generate migration files.
This file MUST exist in the alembic directory.
"""

"""Add view_count to materials table

Revision ID: 8e8f7e4292d8
Revises: ec4262f9abc5
Create Date: 2026-03-28 00:41:57.655497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8f7e4292d8'
down_revision: Union[str, None] = 'ec4262f9abc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('view_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_materials_view_count'), 'materials', ['view_count'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_view_count'), table_name='materials')
    op.drop_column('materials', 'view_count')
    # ### end Alembic commands ###
