"""add_google_drive_fields_v2

Revision ID: af14c9a25161
Revises: bdf0d1b0b2ae
Create Date: 2026-05-05 01:39:48.491341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af14c9a25161'
down_revision: Union[str, None] = 'bdf0d1b0b2ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_attachments', sa.Column('google_drive_file_id', sa.String(length=255), nullable=True))
    op.add_column('assignment_attachments', sa.Column('google_drive_link', sa.String(length=1024), nullable=True))
    op.add_column('assignment_attachments', sa.Column('google_drive_file_name', sa.String(length=255), nullable=True))
    op.add_column('assignment_attachments', sa.Column('google_drive_mime_type', sa.String(length=100), nullable=True))
    
    op.add_column('assignment_submissions', sa.Column('google_drive_file_id', sa.String(length=255), nullable=True))
    op.add_column('assignment_submissions', sa.Column('google_drive_link', sa.String(length=1024), nullable=True))
    op.add_column('assignment_submissions', sa.Column('google_drive_file_name', sa.String(length=255), nullable=True))
    op.add_column('assignment_submissions', sa.Column('google_drive_mime_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'google_drive_mime_type')
    op.drop_column('assignment_submissions', 'google_drive_file_name')
    op.drop_column('assignment_submissions', 'google_drive_link')
    op.drop_column('assignment_submissions', 'google_drive_file_id')
    
    op.drop_column('assignment_attachments', 'google_drive_mime_type')
    op.drop_column('assignment_attachments', 'google_drive_file_name')
    op.drop_column('assignment_attachments', 'google_drive_link')
    op.drop_column('assignment_attachments', 'google_drive_file_id')
    # ### end Alembic commands ###
