"""
alembic/script.py.mako
───────────────────────
Template used by `alembic revision` to generate migration files.
This file MUST exist in the alembic directory.
"""

"""Add course field to Material and Contribution models

Revision ID: b0764e33ea8d
Revises: d20ae0867ce5
Create Date: 2026-03-29 00:58:42.538421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0764e33ea8d'
down_revision: Union[str, None] = 'd20ae0867ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('course', sa.String(length=100), nullable=True))
    op.add_column('materials', sa.Column('course', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_materials_course'), 'materials', ['course'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_course'), table_name='materials')
    op.drop_column('materials', 'course')
    op.drop_column('contributions', 'course')
    # ### end Alembic commands ###
