"""
alembic/script.py.mako
───────────────────────
Template used by `alembic revision` to generate migration files.
This file MUST exist in the alembic directory.
"""

"""add_validation_pipeline_foundation

Revision ID: c1000a8496d7
Revises: b0764e33ea8d
Create Date: 2026-04-14 23:41:36.470358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1000a8496d7'
down_revision: Union[str, None] = 'b0764e33ea8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution_validation_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contribution_id', sa.String(length=36), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=True),
    sa.Column('grammar_details', sa.Text(), nullable=True),
    sa.Column('plagiarism_score', sa.Float(), nullable=True),
    sa.Column('plagiarism_details', sa.Text(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('similarity_details', sa.Text(), nullable=True),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('toxicity_details', sa.Text(), nullable=True),
    sa.Column('metadata_valid', sa.Boolean(), nullable=True),
    sa.Column('metadata_details', sa.Text(), nullable=True),
    sa.Column('ai_generated_probability', sa.Float(), nullable=True),
    sa.Column('ai_generated_details', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contribution_id'], ['contributions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contribution_id')
    )
    op.add_column('contributions', sa.Column('processing_status', sa.Enum('UPLOAD_RECEIVED', 'FILE_STORED', 'TEXT_EXTRACTION_IN_PROGRESS', 'GRAMMAR_CHECK_IN_PROGRESS', 'PLAGIARISM_CHECK_IN_PROGRESS', 'TOXICITY_CHECK_IN_PROGRESS', 'METADATA_VALIDATION_IN_PROGRESS', 'FINAL_SCORING_IN_PROGRESS', 'PROCESSING_COMPLETE', 'SENT_FOR_ADMIN_REVIEW', 'REJECTED', 'PROCESSING_FAILED', name='processingstatus'), nullable=True))
    op.add_column('contributions', sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contributions', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contributions', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contributions', sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contributions', sa.Column('final_recommendation', sa.Enum('APPROVED_FOR_REVIEW', 'NEEDS_MANUAL_REVIEW', 'REJECTED', name='finalrecommendation'), nullable=True))
    op.add_column('contributions', sa.Column('student_feedback_message', sa.Text(), nullable=True))
    # end of manually fixed alter statements
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contributions_processing_status'), table_name='contributions')
    op.drop_column('contributions', 'student_feedback_message')
    op.drop_column('contributions', 'final_recommendation')
    op.drop_column('contributions', 'status_updated_at')
    op.drop_column('contributions', 'processing_completed_at')
    op.drop_column('contributions', 'processing_started_at')
    op.drop_column('contributions', 'uploaded_at')
    op.drop_column('contributions', 'processing_status')
    op.drop_table('contribution_validation_reports')
    # ### end Alembic commands ###
