"""
alembic/script.py.mako
───────────────────────
Template used by `alembic revision` to generate migration files.
This file MUST exist in the alembic directory.
"""

"""category

Revision ID: ca5608bb9454
Revises: c045659ca328
Create Date: 2026-03-28 01:39:57.777737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca5608bb9454'
down_revision: Union[str, None] = 'c045659ca328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributions', sa.Column('category', sa.String(length=50), server_default='notes', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contributions', 'category')
    # ### end Alembic commands ###
