import { useEffect, useState } from 'react';
import api from '../services/api';
import { 
  ShieldAlert, Check, X, FileSearch, Info, AlertTriangle, 
  CheckCircle, Fingerprint, Gauge, Clock, Search, ChevronDown, ListCheck 
} from 'lucide-react';
import { Skeleton, SkeletonTableRow, SkeletonCard } from '../components/common/Skeleton';

export default function Admin() {
  const [activeTab, setActiveTab] = useState('review');
  const [pending, setPending] = useState([]);
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [showReport, setShowReport] = useState(false);
  const [reportData, setReportData] = useState(null);
  const [activeReportId, setActiveReportId] = useState(null);

  const fetchPending = () => {
    api.get('/contributions/pending')
      .then(res => setPending(res.data.items || []))
      .catch(console.error);
  };

  useEffect(() => {
    if (activeTab === 'review') fetchPending();
    if (activeTab === 'logs') fetchLogs();
  }, [activeTab]);

  const fetchLogs = () => {
    api.get('/admin/logs').then(res => setLogs(res.data.logs || [])).catch(console.error);
  };

  const handleReview = async (id, isApproved) => {
    setLoading(true);
    try {
      await api.patch(`/admin/contributions/${id}/review`, { approved: isApproved, admin_notes: "Reviewed" });
      alert(isApproved ? "Approved! Document has been published to the global library." : "Rejected successfully.");
      setShowReport(false);
      fetchPending();
    } catch (err) {
      alert("Error processing review: " + (err.response?.data?.detail || ""));
    } finally {
      setLoading(false);
    }
  };

  const openReport = async (item) => {
    if (!item || !item.id) {
      console.error("ADMIN_REPORT_UI: Attempted to open report with a missing contribution ID.", item);
      return;
    }

    console.log(`ADMIN_REPORT_UI: Requesting technical report for ID: ${item.id}`);
    setActiveReportId(item.id);
    setLoading(true);
    setReportData(null); // Clear stale report data before fetch

    try {
      const res = await api.get(`/admin/contributions/${item.id}/report`);
      console.log("ADMIN_REPORT_UI: Successfully received report payload", res.data);
      setReportData(res.data);
      setShowReport(true);
    } catch (err) {
      console.error("ADMIN_REPORT_UI: Fetch operation failed", err);
      const errorDetail = err.response?.data?.detail || "Failed to load technical report due to a network or server error.";
      alert(errorDetail);
    } finally {
      setLoading(false);
    }
  };

  const getRiskLabel = (score) => {
    if (score === null || score === undefined) return { label: 'N/A', color: 'text-slate-400' };
    if (score < 0.3) return { label: 'LOW', color: 'text-emerald-600' };
    if (score < 0.7) return { label: 'MEDIUM', color: 'text-amber-600' };
    return { label: 'HIGH', color: 'text-red-600' };
  };

  const getQualityLabel = (score) => {
    if (score === null || score === undefined) return { label: 'N/A', color: 'text-slate-400' };
    if (score > 0.8) return { label: 'EXCELLENT', color: 'text-emerald-600' };
    if (score > 0.5) return { label: 'GOOD', color: 'text-blue-600' };
    return { label: 'POOR', color: 'text-red-600' };
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <div className="bg-white dark:bg-slate-900 rounded-3xl shadow-xl border border-slate-100 dark:border-slate-800 p-10 mt-6 relative overflow-hidden transition-colors duration-300">
         <div className="absolute top-0 left-0 w-1.5 h-full bg-red-600"></div>
        <h2 className="text-3xl font-black text-slate-900 dark:text-white flex items-center gap-4 tracking-tight"><ShieldAlert className="text-red-600 w-10 h-10"/> Admin Control Panel</h2>
        <p className="text-slate-500 dark:text-slate-400 text-sm mt-2 mb-8 font-semibold w-2/3">Review student submissions and monitor the physical audit tracking log generated by system events natively.</p>

        <div className="flex gap-4 mb-8">
          <button onClick={() => setActiveTab('review')} className={`px-6 py-2.5 rounded-xl font-bold transition-all text-sm uppercase tracking-wider ${activeTab === 'review' ? 'bg-indigo-600 text-white shadow-md shadow-indigo-200 dark:shadow-none' : 'bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'}`}>Review Queue</button>
          <button onClick={() => setActiveTab('logs')} className={`px-6 py-2.5 rounded-xl font-bold transition-all text-sm uppercase tracking-wider ${activeTab === 'logs' ? 'bg-indigo-600 text-white shadow-md shadow-indigo-200 dark:shadow-none' : 'bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'}`}>System Audit Logs</button>
        </div>
        {activeTab === 'review' && (
          pending.length === 0 ? (
            <div className="text-center py-20 text-slate-400 dark:text-slate-500 font-black bg-slate-50 dark:bg-slate-800/40 rounded-2xl border-2 border-dashed border-slate-200 dark:border-slate-800 uppercase tracking-[0.2em] text-sm shadow-inner">No pending submissions to review</div>
          ) : (
            <>
              {/* Mobile Card View */}
              <div className="md:hidden space-y-4">
                {pending.map((m) => (
                  <div key={m.id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm space-y-4">
                    <div className="flex justify-between items-start">
                      <div>
                        <h3 className="text-lg font-black text-slate-900 dark:text-white leading-tight">{m.title}</h3>
                        <p className="text-xs font-bold text-slate-500 dark:text-slate-400 mt-1 uppercase tracking-wider">{m.category} • Sem {m.semester}</p>
                      </div>
                    </div>
                    
                    <div className="grid grid-cols-2 gap-3">
                      <div className="bg-slate-50 dark:bg-slate-800/60 p-3 rounded-xl border border-slate-100 dark:border-slate-700/50">
                        <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Plagiarism</p>
                        {m.ai_plagiarism_score !== null ? (
                          <span className={`text-xs font-bold ${m.ai_plagiarism_score > 50 ? 'text-red-600 dark:text-red-400' : 'text-emerald-600 dark:text-emerald-400'}`}>{m.ai_plagiarism_score}% Match</span>
                        ) : <span className="text-slate-400 dark:text-slate-500 text-xs font-bold uppercase">Processing</span>}
                      </div>
                      <div className="bg-slate-50 dark:bg-slate-800/60 p-3 rounded-xl border border-slate-100 dark:border-slate-700/50">
                        <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Quality</p>
                        {m.ai_grammar_score !== null ? (
                          <span className={`text-xs font-bold ${m.ai_grammar_score < 50 ? 'text-red-600 dark:text-red-400' : 'text-blue-600 dark:text-blue-400'}`}>{m.ai_grammar_score}/100</span>
                        ) : <span className="text-slate-400 dark:text-slate-500 text-xs font-bold uppercase">Processing</span>}
                      </div>
                    </div>

                    <div className="flex gap-2 pt-2">
                       <button 
                        onClick={() => openReport(m)}
                        className="flex-1 py-3 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-400 rounded-xl font-black text-sm border border-indigo-100 dark:border-indigo-800/40 flex items-center justify-center gap-2"
                      >
                        <FileSearch className="w-4 h-4"/> Report
                      </button>
                      <button 
                        disabled={loading}
                        onClick={() => handleReview(m.id, true)} 
                        className="flex-1 py-3 bg-emerald-600 dark:bg-emerald-700 text-white rounded-xl font-black text-sm shadow-md active:scale-95 flex items-center justify-center gap-2"
                      >
                        <Check className="w-4 h-4"/> Approve
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              {/* Tablet/Desktop Table View */}
              <div className="hidden md:block overflow-x-auto shadow-sm border border-slate-200 dark:border-slate-800 rounded-2xl bg-white dark:bg-slate-900 transition-colors">
                <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-800">
                  <thead className="bg-[#f8fafc] dark:bg-slate-800/40">
                    <tr>
                      <th className="py-5 pl-5 pr-3 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em] sm:pl-6">Document Title</th>
                      <th className="px-3 py-5 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em]">Details</th>
                      <th className="px-3 py-5 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em]">Plagiarism Check</th>
                      <th className="px-3 py-5 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em]">Quality Check</th>
                      <th className="px-8 py-5 text-right text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em] min-w-[140px]">Actions</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-slate-900">
                    {loading && pending.length === 0 ? (
                      [...Array(5)].map((_, i) => (
                        <tr key={i}><td colSpan="5"><SkeletonTableRow columns={5} /></td></tr>
                      ))
                    ) : pending.map((m) => (
                      <tr key={m.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40 transition-colors">
                        <td className="whitespace-nowrap py-5 pl-5 pr-3 text-sm font-extrabold text-slate-900 dark:text-white sm:pl-6">{m.title}</td>
                        <td className="whitespace-nowrap px-3 py-5 text-sm text-slate-500 dark:text-slate-400 font-bold">{m.category} / Sem {m.semester}</td>
                        <td className="whitespace-nowrap px-3 py-5 text-sm">
                           {m.ai_plagiarism_score !== null ? (
                              <span className={`px-4 py-1.5 rounded-full text-xs font-black border ${m.ai_plagiarism_score > 50 ? 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 border-red-200 dark:border-red-900/30' : 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-900/30'}`}>
                                 {m.ai_plagiarism_score}% Match
                              </span>
                           ) : <span className="text-slate-400 font-bold text-xs uppercase tracking-widest bg-slate-100 dark:bg-slate-800 px-3 py-1 rounded">Processing</span>}
                        </td>
                        <td className="whitespace-nowrap px-3 py-5 text-sm">
                            {m.ai_grammar_score !== null ? (
                              <span className={`px-4 py-1.5 rounded-full text-xs font-black border ${m.ai_grammar_score < 50 ? 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 border-red-200 dark:border-red-900/30' : 'bg-blue-50 dark:bg-blue-900/20 text-blue-700 dark:text-blue-400 border-blue-200 dark:border-blue-900/30'}`}>
                                 {m.ai_grammar_score}/100 Score
                              </span>
                           ) : <span className="text-slate-400 font-bold text-xs uppercase tracking-widest bg-slate-100 dark:bg-slate-800 px-3 py-1 rounded">Processing</span>}
                        </td>
                        <td className="whitespace-nowrap px-5 py-5 text-right text-sm font-medium">
                          <div className="flex justify-end gap-3 items-center">
                            <button 
                              onClick={() => openReport(m)}
                              className="p-3 bg-indigo-50 dark:bg-indigo-900/20 text-indigo-700 dark:text-indigo-400 hover:bg-indigo-600 dark:hover:bg-indigo-500 hover:text-white border border-indigo-100 dark:border-indigo-800 rounded-2xl transition-all shadow-sm active:scale-90"
                              title="Technical Report"
                            >
                              <FileSearch className="w-6 h-6"/>
                            </button>
                            <button 
                              disabled={loading}
                              onClick={() => handleReview(m.id, true)} 
                              className="p-3 bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-600 dark:hover:bg-emerald-500 hover:text-white border border-emerald-100 dark:border-emerald-800 rounded-2xl transition-all disabled:opacity-50 shadow-sm active:scale-90 group group-hover:shadow-emerald-100 dark:group-hover:shadow-none" 
                              title="Approve & Publish"
                            >
                              <Check className="w-6 h-6"/>
                            </button>
                            <button 
                              disabled={loading}
                              onClick={() => handleReview(m.id, false)} 
                              className="p-3 bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 hover:bg-red-600 dark:hover:bg-red-500 hover:text-white border border-red-100 dark:border-red-800 rounded-2xl transition-all disabled:opacity-50 shadow-sm active:scale-90 group group-hover:shadow-red-100 dark:group-hover:shadow-none" 
                              title="Reject Submission"
                            >
                              <X className="w-6 h-6"/>
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          )
        )}

        {activeTab === 'logs' && (
          <div className="overflow-hidden shadow-sm border border-slate-200 dark:border-slate-800 rounded-2xl bg-white dark:bg-slate-900 transition-colors">
            <table className="min-w-full divide-y divide-slate-200 dark:divide-slate-800">
              <thead className="bg-[#f8fafc] dark:bg-slate-800/40">
                <tr>
                  <th className="py-5 pl-5 pr-3 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em]">Timestamp</th>
                  <th className="px-3 py-5 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em]">Action Logged</th>
                  <th className="px-3 py-5 text-left text-xs font-black text-slate-600 dark:text-slate-400 uppercase tracking-[0.1em]">Description Detail</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800 bg-white dark:bg-slate-900">
                {loading && logs.length === 0 ? (
                  [...Array(10)].map((_, i) => (
                    <tr key={i}><td colSpan="3"><SkeletonTableRow columns={3} /></td></tr>
                  ))
                ) : logs.map((log) => (
                  <tr key={log.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40 transition-colors">
                    <td className="whitespace-nowrap py-5 pl-5 pr-3 text-sm font-semibold text-slate-500 dark:text-slate-400">{new Date(log.timestamp).toLocaleString()}</td>
                    <td className="whitespace-nowrap px-3 py-5 text-sm font-extrabold text-slate-700 dark:text-slate-200">{log.action}</td>
                    <td className="px-3 py-5 text-sm text-slate-600 dark:text-slate-300 font-medium">{log.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
            {logs.length === 0 && <div className="text-center py-10 text-slate-400 dark:text-slate-500 font-semibold text-sm">No recent logs found.</div>}
          </div>
        )}
      </div>

      {/* Technical Report Modal */}
      {showReport && reportData && (
        <div className="fixed inset-0 bg-slate-900/80 backdrop-blur-md z-[100] flex items-center justify-center p-4">
          <div className="bg-white dark:bg-slate-900 w-full max-w-4xl max-h-[90vh] rounded-[2.5rem] shadow-2xl overflow-hidden flex flex-col border border-slate-200 dark:border-slate-800">
            {/* Header */}
            <div className="p-8 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-[#f8fafc] dark:bg-slate-950/20">
              <div className="flex items-center gap-4">
                <div className="p-3 bg-indigo-600 text-white rounded-2xl shadow-lg shadow-indigo-100 dark:shadow-none">
                  <Fingerprint className="w-8 h-8"/>
                </div>
                <div>
                  <h2 className="text-2xl font-black text-slate-900 dark:text-white leading-tight">Technical Validation Report</h2>
                  <p className="text-sm font-bold text-slate-500 dark:text-slate-400 uppercase tracking-widest mt-0.5">Contribution Audit • {activeReportId.slice(0,8)}</p>
                </div>
              </div>
              <button onClick={() => setShowReport(false)} className="p-3 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-2xl transition-colors text-slate-400 dark:text-slate-500">
                <X className="w-6 h-6"/>
              </button>
            </div>

            {/* Scrollable Content */}
            <div className="flex-1 overflow-y-auto p-10 space-y-12">
              
              {/* 1. Final Decision Summary */}
              <section className="bg-slate-50 dark:bg-slate-800/40 rounded-[2rem] p-8 border border-slate-200 dark:border-slate-800">
                <h3 className="text-xs font-black text-slate-400 dark:text-slate-500 uppercase tracking-[0.2em] mb-6 flex items-center gap-2">
                  <ListCheck className="w-4 h-4"/> Final Decision Summary
                </h3>
                <div className="grid md:grid-cols-3 gap-8">
                  <div className="space-y-1">
                    <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">Recommendation</p>
                    <span className={`inline-block py-1.5 px-4 rounded-full text-xs font-black border ${
                      reportData?.summary?.recommendation === 'APPROVED_FOR_REVIEW' ? 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-700 dark:text-emerald-400 border-emerald-200 dark:border-emerald-900/30' : 
                      reportData?.summary?.recommendation === 'REJECTED' ? 'bg-red-50 dark:bg-red-900/20 text-red-700 dark:text-red-400 border-red-200 dark:border-red-900/30' : 'bg-amber-50 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400 border-amber-200 dark:border-amber-900/30'
                    }`}>
                      {reportData?.summary?.recommendation?.replace(/_/g, ' ') || 'PENDING'}
                    </span>
                  </div>
                  <div className="space-y-1">
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Overall Quality</p>
                    <div className="flex items-center gap-3">
                      <span className="text-xl font-black text-slate-900">{(reportData?.summary?.overall_quality_score * 100 || 0).toFixed(0)}%</span>
                      <span className={`text-[10px] font-black ${getQualityLabel(reportData?.summary?.overall_quality_score).color} uppercase`}>
                        {getQualityLabel(reportData?.summary?.overall_quality_score).label}
                      </span>
                    </div>
                  </div>
                  <div className="space-y-1">
                    <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Overall Risk</p>
                    <div className="flex items-center gap-3">
                      <span className="text-xl font-black text-slate-900">{(reportData?.summary?.overall_risk_score * 100 || 0).toFixed(0)}%</span>
                      <span className={`text-[10px] font-black ${getRiskLabel(reportData?.summary?.overall_risk_score).color} uppercase`}>
                        {getRiskLabel(reportData?.summary?.overall_risk_score).label}
                      </span>
                    </div>
                  </div>
                </div>
                <div className="mt-8 pt-6 border-t border-slate-200">
                   <p className="text-xs font-bold text-slate-600 italic">" {reportData?.summary?.admin_summary || 'No summary available.'} "</p>
                </div>
              </section>

              {/* 2. Layer Analysis Grid */}
              <div className="grid md:grid-cols-2 gap-8">
                
                {/* Plagiarism & Similarity */}
                <div className="space-y-6">
                  <div className="bg-white p-6 rounded-3xl border border-slate-100 shadow-sm">
                    <div className="flex justify-between items-start mb-4">
                      <h4 className="text-sm font-black text-slate-900 flex items-center gap-2"><Search className="w-4 h-4 text-indigo-500"/> Originality & Similarity</h4>
                      <span className={`text-[10px] font-black px-2 py-0.5 rounded border ${getRiskLabel(1 - (reportData?.layers?.plagiarism?.score || 0)).color} bg-slate-50`}>
                        {getRiskLabel(1 - (reportData?.layers?.plagiarism?.score || 0)).label} RISK
                      </span>
                    </div>
                    <div className="space-y-4">
                      <div className="flex justify-between items-center text-xs font-bold">
                         <span className="text-slate-500 dark:text-slate-400">Text Overlap (FAISS)</span>
                         <span className="text-slate-900 dark:text-white">{(reportData?.layers?.plagiarism?.score * 100 || 0).toFixed(1)}% Match</span>
                      </div>
                      <div className="flex justify-between items-center text-xs font-bold">
                         <span className="text-slate-500 dark:text-slate-400">Semantic Paraphrasing</span>
                         <span className="text-slate-900 dark:text-white uppercase">{reportData?.layers?.similarity?.details?.duplicate_risk_level || 'LOW'}</span>
                      </div>
                      {/* Matched Sources Preview */}
                      {reportData?.layers?.plagiarism?.details?.matched_sources?.length > 0 && (
                        <div className="mt-4 p-4 bg-slate-50 dark:bg-slate-800/40 rounded-2xl border border-slate-100 dark:border-slate-800">
                          <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-3">Strongest Matches</p>
                          <div className="space-y-2">
                            {reportData?.layers?.plagiarism?.details?.matched_sources?.slice(0, 2).map((s, idx) => (
                              <div key={idx} className="flex justify-between items-center text-[11px] font-bold">
                                <span className="text-slate-600 dark:text-slate-400 truncate mr-4">• {s.title || 'Unknown Material'}</span>
                                <span className="text-indigo-600 dark:text-indigo-400 shrink-0">{(s.score * 100 || 0).toFixed(0)}%</span>
                              </div>
                            ))}
                          </div>
                        </div>
                      )}
                    </div>
                  </div>

                  <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-sm">
                    <div className="flex justify-between items-start mb-4">
                      <h4 className="text-sm font-black text-slate-900 dark:text-white flex items-center gap-2"><ShieldAlert className="w-4 h-4 text-red-500"/> Content Safety</h4>
                      <span className={`text-[10px] font-black px-2 py-0.5 rounded border ${reportData?.layers?.toxicity?.score < 1 ? 'text-red-600 bg-red-50 dark:bg-red-900/20 border-red-100 dark:border-red-900/30' : 'text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 border-emerald-100 dark:border-emerald-900/30'}`}>
                        {reportData?.layers?.toxicity?.score < 1 ? 'UNSAFE' : 'CLEAN'}
                      </span>
                    </div>
                    <div className="space-y-3">
                       <p className="text-[11px] font-bold text-slate-600 dark:text-slate-300 leading-relaxed">{reportData?.layers?.toxicity?.details?.summary_feedback || 'No content safety issues detected.'}</p>
                       {reportData?.layers?.toxicity?.details?.categories_triggered?.length > 0 && (
                         <div className="flex flex-wrap gap-2 pt-2">
                           {reportData?.layers?.toxicity?.details?.categories_triggered.map(c => (
                             <span key={c} className="bg-red-50 dark:bg-red-900/20 text-red-600 dark:text-red-400 text-[10px] font-black px-2 py-1 rounded uppercase tracking-wider">{c.replace(/_/g, ' ')}</span>
                           ))}
                         </div>
                       )}
                    </div>
                  </div>
                </div>

                {/* Quality & Metadata */}
                <div className="space-y-6">
                  <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-sm">
                    <div className="flex justify-between items-start mb-4">
                      <h4 className="text-sm font-black text-slate-900 dark:text-white flex items-center gap-2"><Gauge className="w-4 h-4 text-blue-500"/> Quality & Language</h4>
                      <span className={`text-[10px] font-black px-2 py-0.5 rounded border ${getQualityLabel(reportData?.layers?.grammar?.score).color} bg-slate-50 dark:bg-slate-800/40 dark:border-slate-800`}>
                        {getQualityLabel(reportData?.layers?.grammar?.score).label}
                      </span>
                    </div>
                    <div className="space-y-3">
                       <div className="flex justify-between text-xs font-bold">
                         <span className="text-slate-500 dark:text-slate-400">Readability Score</span>
                         <span className="text-slate-900 dark:text-white">{reportData?.layers?.grammar?.details?.readability_score || 'N/A'}/100</span>
                      </div>
                      <p className="text-[11px] font-bold text-slate-600 dark:text-slate-300 leading-relaxed mt-2 italic">{reportData?.layers?.grammar?.details?.summary_feedback || 'Quality assessment complete.'}</p>
                    </div>
                  </div>

                  <div className="bg-white dark:bg-slate-900 p-6 rounded-3xl border border-slate-100 dark:border-slate-800 shadow-sm">
                    <div className="flex justify-between items-start mb-4">
                      <h4 className="text-sm font-black text-slate-900 dark:text-white flex items-center gap-2"><ListCheck className="w-4 h-4 text-emerald-500"/> Metadata Alignment</h4>
                      <span className={`text-[10px] font-black px-2 py-0.5 rounded border ${reportData?.layers?.metadata?.valid ? 'text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 border-emerald-100 dark:border-emerald-900/30' : 'text-amber-600 bg-amber-50 dark:bg-amber-900/20 border-amber-100 dark:border-amber-900/30'}`}>
                        {reportData?.layers?.metadata?.valid ? 'MATCH' : 'MISMATCH'}
                      </span>
                    </div>
                    <div className="space-y-3">
                       <p className="text-[11px] font-bold text-slate-600 dark:text-slate-300 leading-relaxed">{reportData?.layers?.metadata?.details?.summary_feedback || 'Metadata validation completed.'}</p>
                       {!reportData?.layers?.metadata?.valid && (
                         <div className="flex flex-wrap gap-2 pt-2">
                           {reportData?.layers?.metadata?.details?.mismatch_issues?.map(m => (
                             <span key={m} className="bg-amber-100 dark:bg-amber-900/20 text-amber-700 dark:text-amber-400 text-[10px] font-black px-2 py-1 rounded uppercase tracking-wider">{m.replace(/_/g, ' ')}</span>
                           ))}
                         </div>
                       )}
                    </div>
                  </div>

                  {/* AI Generated Content Soft Signal */}
                  <div className="bg-[#f0f9ff] dark:bg-blue-950/20 p-5 rounded-3xl border border-blue-100 dark:border-blue-900/40">
                    <div className="flex justify-between items-start mb-3">
                      <h4 className="text-[11px] font-black text-blue-900 dark:text-blue-300 uppercase tracking-widest flex items-center gap-2"><Fingerprint className="w-3 h-3"/> AI Generation Probability</h4>
                      <span className="text-[9px] font-black text-blue-500 dark:text-blue-400 uppercase tracking-tighter">Forensic Advisor</span>
                    </div>
                    <div className="flex items-end justify-between">
                      <div className="space-y-1">
                        <span className="text-2xl font-black text-blue-600 dark:text-blue-400">{(reportData?.layers?.ai_generated?.probability * 100 || 0).toFixed(0)}%</span>
                        <p className="text-[9px] font-bold text-blue-400 dark:text-blue-500 leading-tight pr-4">Pattern Likelihood ({reportData?.layers?.ai_generated?.details?.confidence_level || 'UNKNOWN'} CONFIDENCE)</p>
                      </div>
                      <div className="text-right">
                         <span className="text-[8px] font-black text-blue-300 dark:text-blue-700 block uppercase tracking-widest mb-1 italic">Soft Signal Disclaimer</span>
                         <div className="w-full bg-blue-200 dark:bg-blue-900/40 h-1 rounded-full overflow-hidden">
                           <div className="bg-blue-600 dark:bg-blue-500 h-full" style={{ width: `${(reportData?.layers?.ai_generated?.probability || 0) * 100}%` }}></div>
                         </div>
                      </div>
                    </div>
                  </div>
                </div>
              {/* 3. Timeline */}
              <section className="pt-8 border-t border-slate-100 dark:border-slate-800">
                <div className="flex items-center gap-8 justify-center">
                   <div className="flex flex-col items-center">
                      <Clock className="w-4 h-4 text-slate-300 dark:text-slate-600 mb-2"/>
                      <p className="text-[9px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">Uploaded</p>
                      <p className="text-[10px] font-bold text-slate-600 dark:text-slate-300">{reportData?.timeline?.uploaded_at ? new Date(reportData.timeline.uploaded_at).toLocaleTimeString() : 'N/A'}</p>
                   </div>
                   <div className="w-12 h-[1px] bg-slate-100 dark:bg-slate-800 mb-4"></div>
                   <div className="flex flex-col items-center">
                      <Clock className="w-4 h-4 text-indigo-300 dark:text-indigo-700 mb-2"/>
                      <p className="text-[9px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">Processing</p>
                      <p className="text-[10px] font-bold text-slate-600 dark:text-slate-300">{reportData?.timeline?.processing_started_at ? new Date(reportData.timeline.processing_started_at).toLocaleTimeString() : 'N/A'}</p>
                   </div>
                   <div className="w-12 h-[1px] bg-slate-100 dark:bg-slate-800 mb-4"></div>
                   <div className="flex flex-col items-center">
                      <CheckCircle className="w-4 h-4 text-emerald-400 dark:text-emerald-600 mb-2"/>
                      <p className="text-[9px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest">Completed</p>
                      <p className="text-[10px] font-bold text-slate-600 dark:text-slate-300">{reportData?.timeline?.processing_completed_at ? new Date(reportData.timeline.processing_completed_at).toLocaleTimeString() : 'N/A'}</p>
                   </div>
                </div>
              </section>

            </div>

            {/* Footer Actions */}
            <div className="p-8 bg-slate-50 dark:bg-slate-950/40 border-t border-slate-200 dark:border-slate-800 flex justify-between items-center">
               <div className="flex items-center gap-3">
                  <Info className="w-5 h-5 text-indigo-500 dark:text-indigo-400"/>
                  <p className="text-[11px] font-bold text-slate-500 dark:text-slate-400 w-2/3 leading-tight uppercase tracking-tight">Reviewing this report before approval is recommended to maintain the integrity of the Christ University library.</p>
               </div>
               <div className="flex gap-4">
                 <button 
                   disabled={loading}
                   onClick={() => handleReview(activeReportId, false)}
                   className="px-8 py-3 bg-white dark:bg-slate-800 text-red-600 dark:text-red-400 border border-red-200 dark:border-red-900/40 rounded-2xl font-black text-sm hover:bg-red-50 dark:hover:bg-red-900/20 transition-all shadow-sm active:scale-95"
                 >
                   Reject
                 </button>
                 <button 
                  disabled={loading}
                  onClick={() => handleReview(activeReportId, true)}
                  className="px-10 py-3 bg-emerald-600 dark:bg-emerald-700 text-white rounded-2xl font-black text-sm shadow-xl shadow-emerald-100 dark:shadow-none hover:bg-emerald-700 dark:hover:bg-emerald-800 transition-all active:scale-95 flex items-center gap-2"
                 >
                   <Check className="w-4 h-4"/> Approve & Publish
                 </button>
               </div>
            </div>
          </div>
        </div>
      </div>
    )}
    </div>
  );
}
